# filepath: .github/workflows/ci-cd.yaml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  setup:
    name: Checkout y Setup de dependencias
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias (npm ci)
        run: npm ci
      - name: Instalar dependencias (npm install)
        run: npm install

  format-check:
    name: Chequeo de Formato
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar Prettier
        run: npx prettier --check .

  secret-scan:
    name: Detección de Secretos
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar truffleHog
        uses: trufflesecurity/trufflehog@v3.67.3
        with:
          scanArguments: --no-update --fail

  # docker-build:
  #   name: Build de Imagen Docker
  #   runs-on: ubuntu-latest
  #   needs: [format-check, secret-scan]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Instalar dependencias
  #       run: npm ci
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build Docker image
  #       run: docker build -t my-app:latest .
